--Insert data into operations, account here for test prupose
--DROP ALL OBJECTS;
INSERT INTO CLIENT VALUES (1, 'issam', 'saidi');
INSERT INTO CURRENT_ACCOUNT (ID, OWNER_ID, BALANCE, CURRENCY) VALUES (1,1, 100, 'EURO');
INSERT INTO OPERATION VALUES (1, 'DEPOSIT', 100.00, 'EURO', 1);
INSERT INTO OPERATION VALUES (2, 'WITHDRAW', 25.00, 'EURO', 1);
INSERT INTO OPERATION VALUES (3, 'DEPOSIT', 100.00, 'EURO', 1);
INSERT INTO OPERATION VALUES (4, 'WITHDRAW', 400.00, 'EURO', 1);
